source: ./source
destination: ./site

permalink: /:title.html

defaults:
  -
    scope:
      path: ""
    values:
      project-name: "The Life and Times of You"
      layout: "post"
      author: "Adam Stempniak, Mateusz Dębski, Jakub Świadek"